In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv(r'C:\Users\KIIT\Desktop\ML\datasets_1846_3197_Social_Network_Ads.csv')

In [3]:
data.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [4]:
real_x = data.iloc[:,[2,3]].values#independent
# real_x

In [5]:
real_y=data.iloc[:,4].values
#real_y #dependent

In [6]:
train_x, test_x, train_y , test_y = train_test_split(real_x,real_y,test_size=0.25,random_state=0)


In [7]:
#feature scale hum use karenge kyu ki age and salary ke beech ka numeric difference kaffi jyada hai 

In [8]:
#feature scaling 
#isme age and salary distribute ho jayenge +2 to -2 range ke andr so that data ko plot karne ke liye valid value ho
scaler = StandardScaler()
train_x = scaler.fit_transform(train_x)
test_x = scaler.fit_transform(test_x)
# train_x

In [9]:
# test_x

In [10]:

# import warnings filter
from warnings import simplefilter
# ignore all future warnings
simplefilter(action='ignore', category=FutureWarning)
classifier_lr = LogisticRegression(random_state=0)
classifier_lr.fit(train_x,train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [11]:
y_pred=classifier_lr.predict(test_x)

In [12]:
y_pred
# 0 is no , 1 yes that is can't buy , can buy

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [13]:
test_y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1], dtype=int64)

In [14]:
#confusion matrix hamare liye wrong predicts and right predicts seperate kar ke deta hai

In [15]:
mat = confusion_matrix(test_y,y_pred)
mat#63 and 25 are correct value63+25 
#7,5 are wrong7+5   88% accuracy

array([[63,  5],
       [ 7, 25]], dtype=int64)

In [18]:
##Plotting
from matplotlib.colors import ListedColormap
x_set,y_set = train_x,train_y
x1,x2 = np.meshgrid(np.arange(start = x_set[:, 0].min() - 1,stop = x_set[:, 0].max() +1, step =0.01)
                    np.arange(start = x_set[:, 1].min() - 1,stop = x_set[:, 1].max() +1, step =0.01)
                   plt.contourf(x1,x2,classifier_lr.predict(np.array([x1.ravel(),x2.ravel()]).T).reshape(x1.shape),
                                 alpha = 0.75 ,cmap = ListedColormap(('red','green')))
                   

SyntaxError: invalid syntax (<ipython-input-18-5d6a138edf6c>, line 5)